name: seconds_countdown_timer
description: "package that provide countdown timer with customized widget."
version: 0.2.1
homepage: https://github.com/FakeRaccoon/seconds_countdown_timer

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0